// acceptance-entrypoint-generator <json-ir> <generated-test-output>
//
// Turns parser JSON IR into a thin, executable acceptance test entry point plus
// a metadata file. The entry point embeds the IR path and delegates ALL step
// behavior to the runtime + project step handlers (it contains no application
// bindings of its own). See APS acceptance-generator.md.
//
// Exit codes: 0 success, 1 input/output error, 2 usage error.

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const acceptanceDir = dirname(fileURLToPath(import.meta.url))

function fail(code: number, message: string): never {
  process.stderr.write(`${message}\n`)
  process.exit(code)
}

// Lowercase, collapse runs of non-alphanumerics to one hyphen, trim hyphens.
function metadataName(featurePath: string): string {
  const slug = featurePath
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return `${slug}.json`
}

function featureStem(featurePath: string): string {
  const base = featurePath.split(/[\\/]/).pop() ?? featurePath
  const noExt = base.replace(/\.[^.]+$/, '')
  const slug = noExt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug || 'feature'
}

function main(): void {
  const positionals = process.argv.slice(2)
  if (positionals.length !== 2) {
    fail(2, 'usage: acceptance-entrypoint-generator <json-ir> <generated-test-output>')
  }
  const [irArg, outArg] = positionals as [string, string]
  const irPath = resolve(irArg)
  const outDir = resolve(outArg)

  // Validate the IR is readable JSON before generating anything.
  try {
    JSON.parse(readFileSync(irPath, 'utf8'))
  } catch (err) {
    fail(1, `cannot read IR ${irPath}: ${err instanceof Error ? err.message : String(err)}`)
  }

  const featurePath = process.env.ACCEPTANCE_FEATURE_PATH ?? irArg
  const stem = featureStem(featurePath)

  const generatedFileName = `${stem}_acceptance_test.ts`
  const generatedPath = join(outDir, generatedFileName)

  // Import the runtime by a path RELATIVE to the generated file (resolved
  // against import.meta at run time) and embed the IR arg AS GIVEN. Both are
  // independent of the absolute checkout location, so the generated bytes -
  // and therefore implementation_hash - are stable across machines/worktrees,
  // which keeps the committed differential manifest reusable.
  const runtimeImport = relative(outDir, join(acceptanceDir, 'runtime.ts')).split('\\').join('/')

  const entrypoint = `// GENERATED by acceptance-entrypoint-generator. Do not edit.
import { runIr } from ${JSON.stringify(runtimeImport)}

const irPath = process.env.ACCEPTANCE_IR ?? ${JSON.stringify(irArg)}
const result = runIr(irPath)
process.stdout.write(result.output + '\\n')
process.exit(result.ok ? 0 : 1)
`

  try {
    mkdirSync(outDir, { recursive: true })
    writeFileSync(generatedPath, entrypoint)
  } catch (err) {
    fail(1, `cannot write generated test: ${err instanceof Error ? err.message : String(err)}`)
  }

  // implementation_hash covers ONLY generated acceptance files.
  const hash = createHash('sha256').update(readFileSync(generatedPath)).digest('hex')

  const metadata = {
    schema_version: 1,
    feature_path: featurePath,
    ir_path: irArg,
    implementation_hash: `sha256:${hash}`,
    hash_scope: 'generated_files',
    generated_files: [join(outArg, generatedFileName)]
  }

  try {
    const metadataDir = join(outDir, 'metadata')
    mkdirSync(metadataDir, { recursive: true })
    writeFileSync(join(metadataDir, metadataName(featurePath)), `${JSON.stringify(metadata, null, 2)}\n`)
  } catch (err) {
    fail(1, `cannot write metadata: ${err instanceof Error ? err.message : String(err)}`)
  }

  process.stdout.write(`generated ${generatedPath}\n`)
}

main()
